@baseUrl = http://localhost:3009


# Público
GET {{baseUrl}} HTTP/1.1
Content-Type: text/html

###

# Privado
GET {{baseUrl}}/protegido HTTP/1.1
Content-Type: application/json, text/html
Authorization: mi-token-secreto

###

# Desde el Controller
GET {{baseUrl}}/api/saludo HTTP/1.1
Content-Type: text/html

################################################################
### Region: Login Controller
################################################################
# @name loginAuth
@cookies = {{loginAuth.response.headers.set-cookie}}
POST {{baseUrl}}/login/auth HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "1234",
    "email": "a@a.com"
}

###

# Register a new User
POST {{baseUrl}}/login/register HTTP/1.1
Content-Type: application/json

{
    "username": "Admin",
    "password": "1234",
    "email": "admin@localhost"
}

################################################################
### Region: Books Controller
################################################################

# GetAll
GET {{baseUrl}}/books HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}
###

# GetById
GET {{baseUrl}}/books/2 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Create
POST {{baseUrl}}/books/create HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

# {
#     "title": "El nombre del viento",
#     "author": "Patrick Rothfuss",
#     "image_url": "https://example.com/image.jpg",
#     "genre": "Fantasía",
#     "publisher": "Daw Books",
#     "pages": 662,
#     "published_date": "2007-03-27",
#     "sinopsis": "La historia de Kvothe, el Asesino de Reyes",
#     "reading_time": "20 horas"
# }
# {
#     "title": "El temor de un hombre sabio",
#     "author": "Patrick Rothfuss",
#     "image_url": "https://example.com/image2.jpg",
#     "genre": "Fantasía",
#     "publisher": "Daw Books",
#     "pages": 994,
#     "published_date": "2011-03-01",
#     "sinopsis": "La continuación de la historia de Kvothe",
#     "reading_time": "30 horas"
# }

# {
#     "title": "Las puertas de piedra",
#     "author": "Patrick Rothfuss",
#     "image_url": "https://example.com/image3.jpg",
#     "genre": "Fantasía",
#     "publisher": "Daw Books",
#     "pages": 1000,
#     "published_date": "2007-10-23",
#     "sinopsis": "La esperada conclusión de la trilogía de Kvothe",
#     "reading_time": "TBD"
# }

{
    "title": "El nombre del viento",
    "author": "Patrick Rothfuss",
    "image_url": "https://example.com/image4.jpg",
    "genre": "Fantasía",
    "publisher": "Daw Books",
    "pages": 662,
    "published_date": "2007-03-27",
    "sinopsis": "La historia de Kvothe, el Asesino de Reyes",
    "reading_time": "20 horas"
}

###

# Update    
PUT {{baseUrl}}/books/update/3 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "id": 3,
    "title": "Las puertas de piedra - UPDATED",
    "author": "Patrick Rothfuss - UPDATED",
    "image_url": "https://example.com/image3.jpg - UPDATED",
    "genre": "Fantasía - UPDATED",
    "publisher": "Daw Books - UPDATED",
    "pages": 1009,
    "published_date": "2007-10-29",
    "sinopsis": "La esperada conclusión de la trilogía de Kvothe - UPDATED",
    "reading_time": "TBD - UPDATED"
}

###

# Delete
DELETE {{baseUrl}}/books/delete/3 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

################################################################
### Region: Search Controller
################################################################

# Search Works by query
GET {{baseUrl}}/search/worksearch?q=picasso&work_page=1&work_size=1 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Search specific edition
GET {{baseUrl}}/search/edition/OL13315399M HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Import to db an specific edition
POST {{baseUrl}}/search/import/OL13315399M HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Search Works by title
GET {{baseUrl}}/search/worksearchbytitle?title=quinquela%20martin&work_page=1&work_size=1 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

################################################################
### Region: UserBook Controller
################################################################

# Create userBook
POST {{baseUrl}}/userbook/create HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "userID": 3,
    "booksIDs": "1,2,4,6,7,8"
}

###

# Find Books by User
GET {{baseUrl}}/userbook/3 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Find Users by Book
GET {{baseUrl}}/userbook/book/4 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

# Delete
DELETE {{baseUrl}}/userbook/delete/3/6 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

################################################################
### Region: User Controller
################################################################

# GetAll
GET {{baseUrl}}/users HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# GetById
GET {{baseUrl}}/users/3 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

###

# Create
POST {{baseUrl}}/users/create HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "username": "admin343",
    "password": "1234",
    "email": "a343@a.com"
}

###

# Update    
PUT {{baseUrl}}/users/update/25 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

{
    "username": "admin343 UPDATED",
    "password": "1234",
    "email": "a343@a.com"
}

###

# Delete
DELETE {{baseUrl}}/users/delete/25 HTTP/1.1
Content-Type: application/json
Cookie: {{cookies}}

################################################################
### Region: Upload Controller
################################################################

# upload image (this request doesn´t work yet)
POST {{baseUrl}}/upload/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cookie: {{cookies}}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="C:\Users\accio\Downloads\descargar.jpg"
Content-Type: image/jpg

----WebKitFormBoundary7MA4YWxkTrZu0gW--


###